<a href="https://colab.research.google.com/github/jasmin-lilly/jasmin-lilly/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import datasets
import pandas as pd
import numpy as np

In [ ]:
#Load dataset
iris=datasets.load_iris()
df=pd.read_csv('/content/iris.csv')
print(df)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]


In [ ]:
#Split the data into train and test samples
x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.1)
print("Dataset is split into training and testing...")
print("Size of training data and its label",x_train.shape,y_train.shape)
print("Size of testing data and its label",x_test.shape,y_test.shape)

Dataset is split into training and testing...
Size of training data and its label (135, 4) (135,)
Size of testing data and its label (15, 4) (15,)


In [ ]:
# prints Label no. and their names
for i in range(len(iris.target_names)):
  print("Label", i , "-",str(iris.target_names[i]))


Label 0 - setosa
Label 1 - versicolor
Label 2 - virginica


In [ ]:
#create object of KNN classifer
classifer = KNeighborsClassifier(n_neighbors=3)


In [ ]:
#perform Training
classifer.fit(x_train, y_train)#perform teating
y_pred=classifer.predict(x_test)


In [ ]:
#Display the results
print("Results of Classification using K-nn with K=3")
for r in range(0,len(x_test)):
  print(" sample:", str(x_test[r]), " Actual-label:",str(y_test[r]), " predict-label:", str(y_pred[r]))
print("Classification Accuracy :" , classifer.score(x_test,y_test))


Results of Classification using K-nn with K=3
 sample: [4.9 3.6 1.4 0.1]  Actual-label: 0  predict-label: 0
 sample: [5.9 3.2 4.8 1.8]  Actual-label: 1  predict-label: 2
 sample: [6.  3.4 4.5 1.6]  Actual-label: 1  predict-label: 1
 sample: [4.4 2.9 1.4 0.2]  Actual-label: 0  predict-label: 0
 sample: [4.5 2.3 1.3 0.3]  Actual-label: 0  predict-label: 0
 sample: [5.8 2.6 4.  1.2]  Actual-label: 1  predict-label: 1
 sample: [7.2 3.  5.8 1.6]  Actual-label: 2  predict-label: 2
 sample: [5.7 4.4 1.5 0.4]  Actual-label: 0  predict-label: 0
 sample: [5.  3.5 1.6 0.6]  Actual-label: 0  predict-label: 0
 sample: [5.5 2.4 3.8 1.1]  Actual-label: 1  predict-label: 1
 sample: [6.4 3.1 5.5 1.8]  Actual-label: 2  predict-label: 2
 sample: [6.  2.2 5.  1.5]  Actual-label: 2  predict-label: 1
 sample: [6.5 3.2 5.1 2. ]  Actual-label: 2  predict-label: 2
 sample: [6.5 3.  5.2 2. ]  Actual-label: 2  predict-label: 2
 sample: [6.4 2.8 5.6 2.2]  Actual-label: 2  predict-label: 2
Classification Accuracy 

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print('Confusion Matrix')
print(confusion_matrix(y_test,y_pred))
print('Accuracy Ketrics')
print(classification_report(y_test,y_pred))

Confusion Matrix
[[5 0 0]
 [0 3 1]
 [0 1 5]]
Accuracy Ketrics
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       0.75      0.75      0.75         4
           2       0.83      0.83      0.83         6

    accuracy                           0.87        15
   macro avg       0.86      0.86      0.86        15
weighted avg       0.87      0.87      0.87        15

